theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
rulers = [80, 120]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
